version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - database

   frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  database:
    build: ./database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: expensetrack
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
